# Generated by Django 6.0.2 on 2026-02-27 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('daily_hour_limit', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=3)),
                ('status', models.CharField(default='pendiente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.user')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(default='pendiente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.activity')),
            ],
            options={
                'db_table': 'subtasks',
            },
        ),
        migrations.CreateModel(
            name='RescheduleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_histories', to='api.subtask')),
            ],
            options={
                'db_table': 'reschedule_history',
            },
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='api.subtask')),
            ],
            options={
                'db_table': 'progress_logs',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.user'),
        ),
        migrations.CreateModel(
            name='DailyOverloadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('limit_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overload_events', to='api.user')),
            ],
            options={
                'db_table': 'daily_overload_events',
            },
        ),
    ]
