# Generated by Django 6.0.2 on 2026-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
